-- Add more dummy data for UrbanX platform
-- This migration adds additional complaints, projects, and alerts with Indian locations

-- Insert additional demo complaints with Indian locations
INSERT INTO complaints (title, description, department, severity, status, location, latitude, longitude, submitted_by, contact_info) VALUES
  ('Water Pipeline Burst in Mumbai', 'Major water pipeline burst on Bandra-Worli Sea Link causing water shortage in surrounding areas. Urgent repair needed.', 'water', 'critical', 'in-progress', 'Bandra-Worli Sea Link, Mumbai', 19.0760, 72.8777, 'Rajesh Kumar', 'rajesh.kumar@mumbai.gov.in'),
  ('Power Outage in Delhi Residential Area', 'Complete power outage affecting 200+ homes in Rohini sector. Residents report outage started at 2 AM and still ongoing.', 'electricity', 'high', 'in-progress', 'Rohini Sector 15, Delhi', 28.7320, 77.0880, 'Priya Sharma', 'priya.sharma@email.com'),
  ('Potholed Roads in Bangalore', 'Multiple large potholes on Outer Ring Road causing accidents and vehicle damage. Especially dangerous during monsoon season.', 'roads', 'high', 'pending', 'Outer Ring Road, Bangalore', 12.9716, 77.5946, 'Arun Patel', 'arun.patel@bangalore.gov.in'),
  ('Sewage Overflow in Chennai', 'Sewage overflowing from manholes in T. Nagar area causing health hazards and foul odor. Mosquito breeding concern.', 'water', 'high', 'in-progress', 'T. Nagar, Chennai', 13.0827, 80.2707, 'Kavita Singh', 'kavita.singh@email.com'),
  ('Street Light Malfunction in Hyderabad', 'Over 50 street lights not working in Jubilee Hills area. Increased crime and safety concerns at night.', 'electricity', 'medium', 'pending', 'Jubilee Hills, Hyderabad', 17.3850, 78.4867, 'Mohammed Ali', 'mohammed.ali@hyderabad.gov.in'),
  ('Traffic Signal Failure in Pune', 'Traffic signals at Aundh junction completely malfunctioning. Causing major traffic congestion and accident risk.', 'roads', 'high', 'in-progress', 'Aundh Junction, Pune', 18.5600, 73.8000, 'Sneha Desai', 'sneha.desai@email.com'),
  ('Water Contamination in Kolkata', 'Reports of contaminated water supply in Salt Lake area. Residents experiencing stomach issues and skin rashes.', 'water', 'critical', 'in-progress', 'Salt Lake, Kolkata', 22.5726, 88.3639, 'Amit Banerjee', 'amit.banerjee@kolkata.gov.in'),
  ('Road Construction Delays in Ahmedabad', 'Ongoing road construction on SG Highway causing massive traffic jams. Project timeline exceeded by 3 months.', 'roads', 'medium', 'in-progress', 'SG Highway, Ahmedabad', 23.0225, 72.5714, 'Meera Shah', 'meera.shah@email.com'),
  ('Transformer Failure in Jaipur', 'Main transformer exploded in Malviya Nagar. Power outage affecting entire neighborhood and risk of fire.', 'electricity', 'critical', 'resolved', 'Malviya Nagar, Jaipur', 26.9124, 75.7873, 'Vikram Singh', 'vikram.singh@jaipur.gov.in'),
  ('Drainage Blockage in Surat', 'Heavy monsoon rains causing severe water logging due to blocked drainage system in textile market area.', 'water', 'high', 'in-progress', 'Textile Market, Surat', 21.1702, 72.8311, 'Rashmi Patel', 'rashmi.patel@email.com'),
  ('Bridge Repair Needed in Lucknow', 'Cracks appearing on Gomti Bridge. Structural integrity concerns for heavy vehicles and pedestrians.', 'roads', 'high', 'pending', 'Gomti Bridge, Lucknow', 26.8467, 80.9462, 'Suresh Gupta', 'suresh.gupta@lucknow.gov.in'),
  ('Power Fluctuations in Chandigarh', 'Frequent power fluctuations in Sector 17 causing damage to electronic appliances in commercial area.', 'electricity', 'medium', 'in-progress', 'Sector 17, Chandigarh', 30.7333, 76.7794, 'Anjali Verma', 'anjali.verma@email.com'),
  ('Water Shortage in Indore', 'Acute water shortage in Vijay Nagar area. Residents forced to buy water from private suppliers.', 'water', 'high', 'in-progress', 'Vijay Nagar, Indore', 22.7196, 75.8577, 'Rajendra Jain', 'rajendra.jain@indore.gov.in'),
  ('Road Safety Issues in Bhopal', 'Missing road signs and poor lighting on NH-12 causing frequent accidents, especially at night.', 'roads', 'medium', 'pending', 'NH-12, Bhopal', 23.2599, 77.4126, 'Sunita Mishra', 'sunita.mishra@email.com'),
  ('Electrical Fire Hazard in Nagpur', 'Exposed live wires hanging from poles in Dharampeth area. Risk of electrocution and fire.', 'electricity', 'critical', 'in-progress', 'Dharampeth, Nagpur', 21.1458, 79.0882, 'Prakash Rao', 'prakash.rao@email.com');

-- Insert additional demo projects with Indian locations
INSERT INTO projects (title, description, department, status, priority, location, latitude, longitude, start_date, end_date, budget, progress) VALUES
  ('Mumbai Metro Line 3 Extension', 'Extension of Mumbai Metro from Aarey to CSMT. Includes elevated tracks, stations, and integration with existing rail network.', 'roads', 'active', 'high', 'Mumbai Suburban', 19.0760, 72.8777, '2025-06-01', '2027-12-31', 450000000.00, 65),
  ('Delhi Water Supply Modernization', 'Upgrade water treatment plants and distribution network in Delhi NCR. Includes smart metering and leak detection systems.', 'water', 'active', 'high', 'Delhi NCR', 28.7041, 77.1025, '2025-08-15', '2027-06-30', 280000000.00, 40),
  ('Bangalore Solar City Initiative', 'Install solar panels on 500+ government buildings and create microgrids for energy independence.', 'electricity', 'planning', 'medium', 'Bangalore City', 12.9716, 77.5946, '2026-03-01', '2028-02-28', 150000000.00, 15),
  ('Chennai Coastal Protection', 'Build sea walls and flood barriers along Chennai coastline to protect against rising sea levels and storm surges.', 'water', 'active', 'critical', 'Chennai Coastline', 13.0827, 80.2707, '2025-09-01', '2027-08-31', 320000000.00, 55),
  ('Hyderabad Smart Traffic System', 'Implement AI-powered traffic management system with 200+ smart signals and real-time congestion monitoring.', 'roads', 'active', 'high', 'Hyderabad City', 17.3850, 78.4867, '2025-11-15', '2027-04-30', 180000000.00, 70),
  ('Kolkata Underground Drainage', 'Replace outdated drainage system in central Kolkata with modern underground network to prevent flooding.', 'water', 'planning', 'high', 'Central Kolkata', 22.5726, 88.3639, '2026-01-01', '2028-12-31', 250000000.00, 10),
  ('Pune EV Charging Network', 'Install 500+ electric vehicle charging stations across Pune city with fast-charging capabilities.', 'electricity', 'active', 'medium', 'Pune Metropolitan', 18.5204, 73.8567, '2025-10-01', '2027-03-31', 95000000.00, 45),
  ('Ahmedabad Riverfront Development', 'Rejuvenate Sabarmati Riverfront with walkways, parks, and flood control measures.', 'roads', 'completed', 'high', 'Sabarmati Riverfront', 23.0225, 72.5714, '2024-01-15', '2026-01-10', 120000000.00, 100),
  ('Jaipur Heritage Lighting', 'Install heritage-appropriate LED lighting for Jaipur''s historic monuments and palaces.', 'electricity', 'active', 'medium', 'Jaipur Heritage Zone', 26.9124, 75.7873, '2025-12-01', '2026-11-30', 45000000.00, 60),
  ('Surat Industrial Waste Treatment', 'Build advanced waste treatment facility for industrial effluents to clean Tapi River.', 'water', 'planning', 'high', 'Surat Industrial Area', 21.1702, 72.8311, '2026-04-01', '2028-03-31', 200000000.00, 5),
  ('Lucknow Smart City Infrastructure', 'Implement IoT sensors for waste management, air quality monitoring, and smart street lighting.', 'roads', 'active', 'medium', 'Lucknow City', 26.8467, 80.9462, '2025-07-01', '2027-06-30', 180000000.00, 35),
  ('Chandigarh Green Corridor', 'Create pedestrian and cycle-friendly corridors connecting major parks and institutions.', 'roads', 'planning', 'low', 'Chandigarh City', 30.7333, 76.7794, '2026-02-15', '2027-08-31', 75000000.00, 0),
  ('Indore Lake Conservation', 'Restore and protect Indore''s lakes with water quality improvement and biodiversity enhancement.', 'water', 'active', 'high', 'Indore Lakes', 22.7196, 75.8577, '2025-05-01', '2027-04-30', 95000000.00, 50),
  ('Bhopal Air Quality Monitoring', 'Deploy 100+ air quality sensors across Bhopal with real-time data and pollution control measures.', 'roads', 'active', 'medium', 'Bhopal City', 23.2599, 77.4126, '2025-08-20', '2026-12-31', 65000000.00, 75),
  ('Nagpur Metro Rail Project', 'Construct elevated metro rail system connecting major hubs in Nagpur metropolitan area.', 'roads', 'planning', 'high', 'Nagpur Metro Area', 21.1458, 79.0882, '2026-06-01', '2029-05-31', 400000000.00, 8);

-- Insert additional demo risk alerts with Indian locations
INSERT INTO risk_alerts (title, description, severity, category, location, latitude, longitude, status, reported_by) VALUES
  ('Monsoon Flood Warning - Mumbai', 'Heavy monsoon rains expected to cause severe flooding in low-lying areas of Mumbai. Residents advised to secure belongings.', 'critical', 'Weather', 'Mumbai Coastal Areas', 19.0760, 72.8777, 'active', 'India Meteorological Department'),
  ('Heatwave Alert - Delhi NCR', 'Extreme heatwave conditions with temperatures exceeding 45°C. Risk of heatstroke and water shortage.', 'high', 'Weather', 'Delhi NCR Region', 28.7041, 77.1025, 'active', 'Delhi Disaster Management'),
  ('Construction Crane Collapse Risk', 'Unstable construction crane at Bandra Worli Sea Link project site. High winds pose collapse risk.', 'critical', 'Safety', 'Bandra Worli Sea Link', 19.0760, 72.8777, 'monitoring', 'BMC Safety Inspector'),
  ('Industrial Chemical Spill - Surat', 'Chemical spill from textile dyeing unit contaminating groundwater. Health risk to nearby communities.', 'critical', 'Environmental', 'Surat Industrial Zone', 21.1702, 72.8311, 'active', 'Gujarat Pollution Control'),
  ('Bridge Structural Failure - Lucknow', 'Gomti Bridge showing signs of structural fatigue. Immediate inspection and load restrictions required.', 'high', 'Infrastructure', 'Gomti Bridge, Lucknow', 26.8467, 80.9462, 'active', 'Uttar Pradesh PWD'),
  ('Power Grid Failure Risk - Bangalore', 'Overloaded power grid in tech park area. Risk of cascading blackouts during peak hours.', 'high', 'Infrastructure', 'Electronic City, Bangalore', 12.9716, 77.5946, 'monitoring', 'Karnataka Power Corporation'),
  ('Landslide Warning - Chennai Hills', 'Heavy rains causing landslide risk in hill areas. Evacuation advised for vulnerable zones.', 'high', 'Weather', 'Chennai Hill Stations', 13.0827, 80.2707, 'active', 'Tamil Nadu Disaster Management'),
  ('Air Pollution Crisis - Delhi', 'PM2.5 levels exceeding safe limits by 8x. Respiratory health emergency declared.', 'critical', 'Health', 'Delhi Metropolitan Area', 28.7041, 77.1025, 'active', 'Central Pollution Control Board'),
  ('Dam Overflow Risk - Hyderabad', 'Hussain Sagar lake at 95% capacity. Risk of overflow during forecast rains.', 'critical', 'Weather', 'Hussain Sagar, Hyderabad', 17.3850, 78.4867, 'active', 'Telangana Irrigation Department'),
  ('Traffic Accident Cluster - Pune', 'Multiple fatal accidents at Sinhagad Road junction. Immediate traffic engineering intervention needed.', 'high', 'Safety', 'Sinhagad Road Junction', 18.5204, 73.8567, 'active', 'Pune Traffic Police'),
  ('Water Contamination Alert - Kolkata', 'Bacterial contamination detected in municipal water supply. Boiling advisory issued.', 'critical', 'Health', 'Kolkata Municipal Supply', 22.5726, 88.3639, 'active', 'Kolkata Municipal Corporation'),
  ('Earthquake Preparedness - Gujarat', 'Increased seismic activity detected. All emergency services on high alert.', 'medium', 'Natural Disaster', 'Gujarat Seismic Zone', 23.0225, 72.5714, 'monitoring', 'National Disaster Management'),
  ('Forest Fire Risk - Madhya Pradesh', 'Dry conditions and high temperatures increasing forest fire risk in Bhopal forests.', 'high', 'Environmental', 'Bhopal Forest Areas', 23.2599, 77.4126, 'active', 'Forest Department MP'),
  ('Cyber Attack on Power Grid - Maharashtra', 'Suspicious network activity detected in state power grid. Cybersecurity team investigating.', 'critical', 'Cybersecurity', 'Maharashtra Power Grid', 19.0760, 72.8777, 'active', 'Maharashtra State Electricity'),
  ('Oil Spill in Port - Chennai', 'Oil tanker leak in Chennai port. Environmental cleanup and marine life protection measures initiated.', 'high', 'Environmental', 'Chennai Port Area', 13.0827, 80.2707, 'active', 'Chennai Port Authority'),
  ('Building Collapse Risk - Old Delhi', 'Historic buildings in Chandni Chowk showing structural cracks. Immediate evacuation ordered.', 'critical', 'Safety', 'Chandni Chowk, Delhi', 28.7041, 77.1025, 'active', 'Delhi Urban Development'),
  ('Drought Conditions - Rajasthan', 'Severe drought affecting water supply in Jaipur rural areas. Water rationing implemented.', 'high', 'Weather', 'Jaipur Rural Districts', 26.9124, 75.7873, 'active', 'Rajasthan Water Resources'),
  ('Pest Outbreak - Punjab', 'Locust swarm approaching Chandigarh. Agricultural and urban areas at risk.', 'medium', 'Agricultural', 'Punjab Border Areas', 30.7333, 76.7794, 'monitoring', 'Punjab Agriculture Department'),
  ('Radiation Leak - Nuclear Facility', 'Minor radiation leak detected at research facility. Containment protocols activated.', 'critical', 'Health', 'Nuclear Research Site', 12.9716, 77.5946, 'active', 'Atomic Energy Commission'),
  ('Stampede Risk - Religious Festival', 'Large crowd gathering expected at religious festival. Crowd management plan activated.', 'high', 'Safety', 'Festival Grounds', 26.8467, 80.9462, 'monitoring', 'District Administration'),
  ('Gas Pipeline Rupture - Industrial Area', 'Natural gas pipeline rupture in industrial estate. Evacuation zone of 2km established.', 'critical', 'Infrastructure', 'Nagpur Industrial Estate', 21.1458, 79.0882, 'active', 'Gas Authority of India');</content>
<parameter name="filePath">c:\Users\hp\Documents\Projects\UrbanX2-main\supabase\migrations\20260117174940_add_more_dummy_data.sql